# Generated by Django 4.0.5 on 2022-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_feedback_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
