# Generated by Django 4.0.5 on 2022-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_alter_contactus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
